First Run
keerthivasansa/cf-bot pull request #2
Opened 2024-10-12 18:28 UTC by BakuDoriya-KatsZuku

2024-10-22 18:19 UTC, keerthivasansa requested changes

2024-10-22 18:19 UTC, keerthivasansa commented on src/discord/commands/speed.ts
> +        // .addBooleanOption(option => option
Remove these comments

2024-10-22 18:19 UTC, keerthivasansa commented on src/discord/commands/speed.ts
> +// import { ratingCmd } from "./rating";
remove unnecessary imports

2024-10-22 18:19 UTC, keerthivasansa commented on src/discord/commands/speed.ts
> +            currentValue[1]++;
(optional) make the values clearer

current.sum  += relativeTimeInMinutes
curr.count++

is easier to read
similarly change the map definition too and the final map creation.

2024-10-22 18:19 UTC, keerthivasansa commented on src/discord/commands/speed.ts
> +        const finalData: Map<number, number> = new Map();
Better name - `ratingTimeMap`

2024-10-22 18:19 UTC, keerthivasansa commented on src/discord/commands/speed.ts
> +        const sortedByKey = new Map([...selectedData.entries()].sort((a, b) => a[0] - b[0]));
Better name: `sortedByRating`

2024-10-22 18:20 UTC, keerthivasansa commented
Also solve merge conflicts in `bun.lockb`

2024-10-27 11:45 UTC, BakuDoriya-KatsZuku commented on src/discord/commands/speed.ts
> +// import { ratingCmd } from "./rating";
Done

2024-10-27 12:59 UTC, keerthivasansa requested changes

2024-10-27 12:59 UTC, keerthivasansa commented on src/discord/commands/stalk.ts
> +                const timeAgo = (timeInS: number): string => {
this should be a util function

2024-10-27 12:59 UTC, keerthivasansa commented on src/discord/commands/stalk.ts
> +            if (rating < 1200) return "🔘";
maybe move this too to some tableUtils.ts within codeforces folder

2024-10-27 12:59 UTC, keerthivasansa commented on src/discord/commands/stalk.ts
> +            const words = text.split(' ');
this should be in utils/string.ts

2024-10-27 12:59 UTC, keerthivasansa commented on src/discord/commands/stalk.ts
> +                const timeAgo = (timeInS: number): string => {
maybe in utils/date.ts

2024-10-27 12:59 UTC, keerthivasansa commented on user_rating.json
> +[["2024-08-30T17:05:00.000Z",1664],["2024-09-20T16:35:00.000Z",1601],["2024-09-27T16:05:00.000Z",1609],["2024-09-29T17:35:00.000Z",1667],["2024-10-13T21:35:00.000Z",1557],["2024-10-14T16:35:00.000Z",
delete this file

2024-10-28 18:11 UTC, keerthivasansa approved these changes

2024-10-28 18:12 UTC, merged