Alert feature complete
keerthivasansa/cf-bot pull request #9
Opened 2024-11-11 16:37 UTC by Dark-Knight499

updates alert.ts

2024-11-15 05:05 UTC, keerthivasansa requested changes

2024-11-15 05:05 UTC, keerthivasansa commented on src/discord/alert.ts
> +alertNewLevel("Harsh",1200,1000)
Can you remove this?

2024-11-15 05:17 UTC, Dark-Knight499 commented on src/discord/alert.ts
> +alertNewLevel("Harsh",1200,1000)
Done. Please check.

2024-11-16 09:09 UTC, keerthivasansa commented
Can you resolve the conflicts? or I can do them if you want.

2024-11-16 10:59 UTC, Dark-Knight499 commented
Resolved them

2024-11-17 02:04 UTC, keerthivasansa commented
awesome

2024-11-17 02:04 UTC, keerthivasansa approved these changes

2024-11-17 02:05 UTC, merged